### ISSUE TITLE
Task: Make API route for Challenge page

### ISSUE THREAD

**Issue by jalikat3** [Developer-DUCS/eMission#57]
1. Put sample challenges in challenge table.
2. There will be 1-2 or more routes added to server /getChallenges, /acceptChallenges
3. Replace premade challenges on challenge page with a pull request to the challenge table to get available challenges. 
4. On select of challenges, submit to AcceptedChallenges table.
5. Look at insertUser and the create User (previously login) page to see how to change the front end for that

**Comment by cwarren279** [comment]
https://docs.carboninterface.com/#/ <-----  LOOK AT THIS our api calls have a beginning but they are currently looking up to json instead of carbon interface. We need api calls converted back to talk directly to carbon API to get this information BUT LIMIT THE TIMES YOU DO THIS as we get like 200 api calls a month. Eventually we will store the car's vehicle ID in the sql database so that each time they drive it doesn't need 3 api calls, only 1.
